version: 0.0.1
service:
  host: localhost
  port: 8989
  write-timeout-seconds: 20
  read-timeout-seconds: 20
  idle-timeout-seconds: 60
  api-command-buffer: 100
usage: application
short-description: short description
long-description: longer description
log-file-path: ./log/trend-risk.log
log-level: DEBUG
postgres:
  server: localhost
  port: 55432
  database: marketdata
  user: marketdata
  pass: m4rk3tdAtA
  sslmode: require
strategy:
  trendrisk:
    database-timeout-seconds: 30
    symbols:
      dax:
        trading-hours:
          Timezone: local
          Sunday:
            - OpenTime: 00:00
              CloseTime: 00:00
          Monday:
            - OpenTime: 01:15
              CloseTime: 22:05
          Tuesday:
            - OpenTime: 01:15
              CloseTime: 22:05
          Wednesday:
            - OpenTime: 01:15
              CloseTime: 22:05
          Thursday:
            - OpenTime: 01:15
              CloseTime: 22:05
          Friday:
            - OpenTime: 01:15
              CloseTime: 22:05
          Saturday:
            - OpenTime: 00:00
              CloseTime: 00:00
      ym:
        trading-hours:
          Timezone: local
          Sunday:
            - OpenTime: 17:00
              CloseTime: 23:59
          Monday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Tuesday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Wednesday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Thursday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Friday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
          Saturday:
            - OpenTime: 00:00
              CloseTime: 00:00
      nq:
        trading-hours:
          Timezone: local
          Sunday:
            - OpenTime: 17:00
              CloseTime: 23:59
          Monday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Tuesday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Wednesday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Thursday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Friday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
          Saturday:
            - OpenTime: 00:00
              CloseTime: 00:00
      es:
        trading-hours:
          Timezone: local
          Sunday:
            - OpenTime: 17:00
              CloseTime: 23:59
          Monday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Tuesday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Wednesday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Thursday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
            - OpenTime: 17:00
              CloseTime: 23:59
          Friday:
            - OpenTime: 00:00
              CloseTime: 15:15
            - OpenTime: 15:30
              CloseTime: 16:00
          Saturday:
            - OpenTime: 00:00
              CloseTime: 00:00
