version: 0.0.1
service:
  host: localhost
  port: 8989
  write-timeout-seconds: 20
  read-timeout-seconds: 20
  idle-timeout-seconds: 60
  api-command-buffer: 100
usage: application
short-description: short description
long-description: longer description
log:
  filepath: ./log/myapp.log
  level: DEBUG
  max-size: 100
  max-backup: 5
  max-age: 30
  compress: true
