package config

const (
	// VersionKey is the application.yaml key for retrieving application version number
	VersionKey = "version"
	// ServiceNameKey is the application.yaml key for retrieving the service name
	ServiceNameKey = "service.name"
	// ServiceHostKey is the application.yaml key for retrieving the service host, i.e. the host exposed by the service
	ServiceHostKey = "service.host"
	// ServicePortKey is the application.yaml key for retrieving the port to run the service on
	ServicePortKey = "service.port"
	// ServiceCommandBufferKey is the application.yaml key for retrieving the size of the command buffer for sending control messages to the service thread
	ServiceCommandBufferKey = "service.api-command-buffer"
	// ServiceWriteTimeoutKey is the application.yaml key for retrieving the write timeout for the server
	ServiceWriteTimeoutKey = "service.write-timeout-seconds"
	// ServiceReadTimeoutKey is the application.yaml key for retrieving the read timeout for the server
	ServiceReadTimeoutKey = "service.read-timeout-seconds"
	// ServiceIdleTimeoutKey is the application.yaml key for retrieving the idle timeout for the server
	ServiceIdleTimeoutKey = "service.idle-timeout-seconds"
	// LogFilePathKey is the application.yaml key for retrieving the path for the log file generated by the service
	LogFilePathKey = "log-file-path"
	// LogLevelKey is the application.yaml key for retrieving the logging level
	LogLevelKey = "log-level"
)
